<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="checkOut.aspx.cs" Inherits="TH03_WebBanHang.checkOutOrder.checkOut" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>KStore</title>
       <link href="Styles/bootstrap.min.css" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
   <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
   <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
       <link rel="preconnect" href="https://fonts.googleapis.com">
       <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
       <link href="https://fonts.googleapis.com/css2?family=Basic&display=swap" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
       <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

</head>
<body>
    <form id="form1" runat="server" class="container">
        <div>

        </div>
        <div class="col-sm-12 justify-content-center align-content-center" style="text-align:center;">


            <div class="loadingio-spinner-dual-ball-2by998twmg8"><div class="ldio-yzaezf3dcmj">
            <div></div><div></div><div></div>
            </div></div>
            <style type="text/css">
            @keyframes ldio-yzaezf3dcmj-o {
                0%    { opacity: 1; transform: translate(0 0) }
               49.99% { opacity: 1; transform: translate(80px,0) }
               50%    { opacity: 0; transform: translate(80px,0) }
              100%    { opacity: 0; transform: translate(0,0) }
            }
            @keyframes ldio-yzaezf3dcmj {
                0% { transform: translate(0,0) }
               50% { transform: translate(80px,0) }
              100% { transform: translate(0,0) }
            }
            .ldio-yzaezf3dcmj div {
              position: absolute;
              width: 80px;
              height: 80px;
              border-radius: 50%;
              top: 60px;
              left: 20px;
            }
            .ldio-yzaezf3dcmj div:nth-child(1) {
              background: #e96e0c;
              animation: ldio-yzaezf3dcmj 1s linear infinite;
              animation-delay: -0.5s;
            }
            .ldio-yzaezf3dcmj div:nth-child(2) {
              background: #b046f0;
              animation: ldio-yzaezf3dcmj 1s linear infinite;
              animation-delay: 0s;
            }
            .ldio-yzaezf3dcmj div:nth-child(3) {
              background: #e96e0c;
              animation: ldio-yzaezf3dcmj-o 1s linear infinite;
              animation-delay: -0.5s;
            }
            .loadingio-spinner-dual-ball-2by998twmg8 {
              width: 200px;
              height: 200px;
              display: inline-block;
              overflow: hidden;
              background: #ffffff;
            }
            .ldio-yzaezf3dcmj {
              width: 100%;
              height: 100%;
              position: relative;
              transform: translateZ(0) scale(1);
              backface-visibility: hidden;
              transform-origin: 0 0; /* see note above */
            }
            .ldio-yzaezf3dcmj div { box-sizing: content-box; }
            /* [ldio] generated by https://loading.io */
            </style>
            <p>Đang trong quá trình xác nhận và xuất đơn...</p>
        </div>
    </form>
</body>
</html>
